### ISSUE TITLE
UI：Chart style display is not normal

### ISSUE THREAD

**Issue by e8tg001** [zinclabs/openobserve#718]
### Which ZincObserve functionalities are the source of the bug?

dashboards

### Is this a regression?

Yes

### Description

After narrowing down to the taskbar, after a few minutes , open page, the chart shows a blank
![image](https://github.com/zinclabs/zincobserve/assets/40289299/11577e86-1380-4a92-843f-17714a523e8c)

### Please provide the version you discovered this bug in (check about page for version information)

```true
version:v0.4.2
```

**Comment by ktx-kirtan** [comment]
@prabhatsharma fixed with #723
